AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'

Documentation:
  # Checks if the top level modules / classes have a comment.
  Enabled: false

# Checks style of children classes and modules.
Style/ClassAndModuleChildren:
  Enabled: true
  SupportedStyles:
    - nested
