inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
inherit_from: .rubocop_todo.yml # Writes a file with the offenses detected and excludes the affected files from future executions.

# DISABLED COPS.
Documentation: # Checks if the top level modules / classes have a comment.
  Enabled: false
OrderedGems:   # Checks if the gems are ordered alfabetically.
  Enabled: false
EmptyLinesAroundAccessModifier: # Removes blank lines around access modifiers (private/protected).
  Enabled: false
StringLiterals: # Prefers double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  DisabledByDefault: true
  Exclude:
    - db/**/*
    - log/**/*
    - tmp/**/*
    - docker/**/*
    - node_modules/**/*
    - bin/**/*

Style/ClassAndModuleChildren:
  Enabled: true
  SupportedStyles:
    - nested

Metrics/LineLength:
  Enabled:         true
  Max:             150
  IgnoredPatterns: [ '(\A|\s)#' ] # Ignores comments.

Metrics/MethodLength:
  Enabled: true
  Max:     50
