version: '2'

services:

  postgres:
    image: 'postgres:9.5'
    env_file:
      - './config/env/postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image:   'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: ./bin/start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/noisu'
    volumes_from: # Mounts the "/bundle" volume of the "bundle" image in "/bundle" inside this container.
      - bundle
    env_file:
      - './config/env/web'

  bundle:
    image: busybox
    volumes:
      - /bundle

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/noisu'
    env_file:
      - './config/env/web'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/noisu'
    env_file:
      - './config/env/web'

volumes:
  redis:
  postgres:
