version: '3.3'

services:

  web:
    build:
      dockerfile: ./docker/web.dev.dockerfile
    depends_on:
      - webpack
    volumes:
      # SSH files to communicate with the outer world within the web container.
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ~/.ssh/authorized_keys:/root/.ssh/authorized_keys

  sidekiq:
    build:
      dockerfile: ./docker/web.dev.dockerfile

  cable:
    build:
      dockerfile: ./docker/web.dev.dockerfile

  webpack:
    build:
      context: .
      dockerfile: ./docker/web.dev.dockerfile
    env_file: ./.env
    command:  ./docker/scripts/start-webpack-dev.sh
    ports:
      - ${WEBPACK_PORT?}:${WEBPACK_PORT?}
    volumes:
      - bundle_cache:/bundle
      - .:/noisu
