version: '3'

volumes:

  bundle_cache:
  redis:
  postgres:

services:

  web:
    build:
      context:    .
      dockerfile: ./docker/web.dockerfile
      args:
        precompile_assets: 'not'
    env_file:   ./.env
    command:    ./docker/scripts/start-web.sh
    tty:        true
    stdin_open: true
    depends_on:
      - postgres
      - redis
      - sidekiq
      - cable
      - webpack
    ports:
      - ${BIND_ON_PORT?}:${BIND_ON_PORT?}
    volumes:
      - bundle_cache:/bundle
      - .:/noisu
      # SSH files to communicate with the outer world within the web container.
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ~/.ssh/authorized_keys:/root/.ssh/authorized_keys

  postgres:
    image:    postgres:11-alpine
    env_file: ./.env
    restart:  always
    ports:
      - ${POSTGRES_PORT?}:${POSTGRES_PORT?}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    build:
      context:    .
      dockerfile: ./docker/redis.dockerfile
    env_file: ./.env
    command:  ./docker/scripts/start-redis.sh
    ports:
      - ${REDIS_PORT?}:${REDIS_PORT?}
    volumes:
      - redis:/var/lib/redis/data

  sidekiq:
    build:
      context:    .
      dockerfile: ./docker/web.dockerfile
    env_file: ./.env
    command:  ./docker/scripts/start-sidekiq.sh
    depends_on:
      - postgres
      - redis
    volumes:
      - bundle_cache:/bundle
      - .:/noisu

  cable:
    build:
      context:    .
      dockerfile: ./docker/web.dockerfile
    env_file: ./.env
    command:  ./docker/scripts/start-cable.sh
    depends_on:
      - redis
    ports:
      - ${ACTION_CABLE_PORT?}:${ACTION_CABLE_PORT?}
    volumes:
      - bundle_cache:/bundle
      - .:/noisu

  webpack:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    env_file: ./.env
    command:  ./docker/scripts/start-webpack-dev.sh
    ports:
      - ${WEBPACK_PORT?}:${WEBPACK_PORT?}
    volumes:
      - bundle_cache:/bundle
      - .:/noisu
