version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: "Setting up the test environment"
          command: |
            cp .env.example .env
            make test_setup
      - save_cache:
          key: gem-cache-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - ./.bundle
      - run:
          name: "Setup Code Climate test-reporter"
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: "Running test"
          command: |
            ./cc-test-reporter before-build
            make test
            ./cc-test-reporter after-build --prefix /opt/app