development: &default
  adapter: redis
  url:     "<%= "redis://:#{ENV["REDIS_PASSWORD"]}@#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/#{ENV["REDIS_NAMESPACE"]}" %>"

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
