development: &default
  adapter:  postgresql
  host:     <%= ENV["POSTGRES_HOST"] %>
  port:     <%= ENV["POSTGRES_PORT"] %>
  user:     <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  encoding: <%= ENV["POSTGRES_ENCODING"] %>
  pool:     <%= ENV["POSTGRES_POOL"] %>
  timeout:  <%= ENV["POSTGRES_TIMEOUT"] %>
  database: noisu_development

test:
  <<: *default
  database: noisu_test

staging:
  <<: *default
  database: noisu_staging

production:
  <<: *default
  database: noisu_production
