# NOTE: You must restart bin/webpack-dev-server for changes to take effect.

default: &default
  source_path:        app/webpacker
  source_entry_path:  packs
  cache_path:         tmp/cache/webpacker
  resolved_paths:     []

development:
  <<: *default
  compile:            true
  public_output_path: packs-development
  cache_manifest:     false
  dev_server:
    https:              false
    host:               webpack
    port:               3035
    public:             webpack:3035
    hmr:                true
    inline:             true         # Inline should be set to true if using HMR.
    overlay:            true
    compress:           true
    disable_host_check: true
    use_local_ip:       false
    quiet:              false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/

test:
  <<: *default
  compile:            true
  public_output_path: packs-test
  cache_manifest:     false

staging:
  <<: *default
  compile:            false
  cache_manifest:     true
  public_output_path: packs-staging

production:
  <<: *default
  compile:            false
  cache_manifest:     true
  public_output_path: packs-production
