default: &default
  source_path:              app/webpacker
  source_entry_path:        packs
  public_root_path:         public
  cache_path:               tmp/cache/webpacker
  resolved_paths:           []
  webpack_compile_output:   false
  extract_css:              false
  check_yarn_integrity:     false
  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  extensions:
    - .erb
    - .js.erb
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  public_output_path: packs-development
  compile:            true
  cache_manifest:     false
  dev_server:
    # Host and port are set in the "webpack-dev-server" run script, as it's impossible to convert this file to ERB
    # and therefore retrieve them from an env var. Explanation: https://github.com/rails/webpacker/issues/956
    https:              false
    hmr:                true
    inline:             true         # Inline should be set to true if using HMR.
    overlay:            true
    compress:           true
    disable_host_check: true
    use_local_ip:       false
    quiet:              false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  public_output_path: packs-test
  compile:            true
  cache_manifest:     false

staging:
  <<: *default
  public_output_path: packs-staging
  compile:            false
  cache_manifest:     true

production:
  <<: *default
  public_output_path: packs-production
  compile:            false
  cache_manifest:     true
