apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  labels:
    app: noisu
spec:
  replicas: 1
  selector:
    app: noisu
    tier: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: noisu
        tier: postgres
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:11-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-user
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: POSTGRES_DB
          value: noisu_production
        - name: PGDATA
          value: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-pv
